### ISSUE TITLE
Add `fastago transform replace` subcommand

### ISSUE THREAD

**Issue by lucblassel** [lucblassel/fastago#3]
The `fastago transform replace` subcommand would be used to replace a given character in all sequences by another one. 
For example to replace all  unknown characters `N` by gaps we could use: 
```
cat input.fasta | fastago transform replace N '-'
```

Alternatively we could also replace motifs in a sequence by using a regular expression.

**Comment by garg-saurav** [comment]
I think it would be better if we use `fastago transform replace` for this
